### ISSUE TITLE
issue exporting journal level entries

### ISSUE THREAD

**Issue by johnp2686** [two-pack/redmine_xls_export#47] opened 2014-03-11 11:34 UTC
Hello,
   Issue exporting journal history  level entries in single spreadsheet i did some modifications in your plugins .I get all issue journal histories but it is exporting separate separate spreadsheets ,I need single spreadsheet in all journal histories
I did modified code below:
location plugin/lib/xls_export.rb

def journal_details_to_xls(issue)

```
    issue_updates = issue.journals.all(:include => [:user, :details], :order => "#{Journal.table_name}.created_on ASC")
    return nil if issue_updates.size == 0
    Spreadsheet.client_encoding = 'UTF-8'
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet(:name => "%05i - Journal" % [issue.id])
    columns_width = []
    sheet1.row(0).replace []
 ['#',l(:field_issue),l(:field_tracker),l(:field_priority),l(:field_created_on),l(:field_updated_on),l(:field_user),l(:field_status_from),l(:field_status_to)].each do |c|
      sheet1.row(0) << c
      columns_width << (get_value_width(c)*1.1)
    end
    sheet1.column(0).default_format = Spreadsheet::Format.new(:number_format => "0")
    idx=0
    issue_updates.each do |journal|
        row = sheet1.row(idx+1)
        row.replace []
     journal.details.each do |detail|
```

  if detail.prop_key =="status_id"
[idx+1,issue.id,issue.tracker_id,issue.priority_id,issue.created_on,journal.created_on,journal.user.name,detail.old_value,detail.value,].each_with_index do
 |e,e_idx|
              lf_pos = get_value_width(e)
              columns_width[e_idx] = lf_pos unless columns_width[e_idx] = lf_pos
              row << e
            end

```
        idx=idx+1
      end
    end
```

end
        update_sheet_formatting(sheet1,columns_width)
       xls_stream = StringIO.new('')
        book.write(xls_stream)
        xls_stream.string
      end

---

**Comment by two-pack** [comment] 2014-05-13 09:25
Is your request that all issues journal history are exported to a file?
What is the purpose of this request format? How to use it? And Is it useful for all users?

**Comment by johnp2686** [comment] 2014-05-15 04:45
it is useful for all users why because when export overall report task new-> progress->resolved ->closed get spent time for state  it is very useful

**Comment by two-pack** [comment] 2014-05-15 05:15
Do you want to get issues status history and NOT need to get journal details and note in same row (like #41 image)?

**Comment by johnp2686** [comment] 2014-05-15 05:20
see the journal history have the status changed details  #41 i added first image did u see that we calculated  based on created_on and update_on it is very useful can u help me

**Comment by two-pack** [comment] 2014-05-15 05:40
Now journal history is exported in pairs of histories in Issue page.
I think your feature needs other way to export. For example, add new button in Detailed page.

**Comment by johnp2686** [comment] 2014-05-15 05:42
yes

**Comment by johnp2686** [comment] 2014-05-15 05:43
And then issue have many journal history we get all the history and we calculated

**Comment by two-pack** [comment] 2014-05-19 04:26
I consider this feature's specification.
- Export XLS file like following images (Especially columns) . 
  ![xls](https://cloud.githubusercontent.com/assets/378981/3009940/4ba4346a-df0c-11e3-84e6-b8efcb7ba4dd.png)
  - I think columns in #41 are duplicated status **from** and another row's **to**. And Priority hasn't **to** and **from**. Above columns are enough to calculate status changed time.
- **Export status histories** setting is added to **Extra options**.
  ![settings](https://cloud.githubusercontent.com/assets/378981/3009974/ba59a7a4-df0d-11e3-90ea-cd4a310779f9.png)
- XLS file is included in Zip file with name of **status_histories.xls**.
- The file has a row the issue is created.
- The file has rows the issue status is updated.
- The file includes all issues status of exported query.

**Comment by johnp2686** [comment] 2014-05-19 04:58
Thanks very much it is very great full

**Comment by two-pack** [comment] 2014-05-20 06:18
> The file has a row the issue is created.

I notice I can't know issue's status and priority when it created. So The file has only rows of updated status ( except a row the issue is created).
And by same reason, priority column leaves. For example, first row is set changed status, I can't know priority this time.
I think columns which is able to add to this sheet are informations related the issue at the moment like project name.

**Comment by two-pack** [comment] 2014-05-20 07:28
I implement this feature. 
Can you check it? After checking it, I'll close this issue and #44 if its ok.

**Comment by johnp2686** [comment] 2014-05-20 10:10
![error](https://cloud.githubusercontent.com/assets/951104/3025541/e53a1be4-e006-11e3-97e8-24be7b3896f4.png)
I am trying to expert it is hitting error

**Comment by two-pack** [comment] 2014-05-21 02:26
Thank you for checking.
I tried to fix the error. Please check it again.

**Comment by johnp2686** [comment] 2014-05-26 05:48
Thanks for response , it is generated status history successfully and one more thing you set(issue ,project,updated(created)on,status) but i need (issue_id,project,created on,updated_on,old status and new status like )

**Comment by two-pack** [comment] 2014-05-26 09:00
> i need (issue_id,project,created on,updated_on,old status and new status like )

I change followings with above commit:
- Adds columns, **Issue created** and **Old status(Status from)**, in status histories.
- Changes column name **Updated(Created) on** to **Updated**.
- Changes column name **Status** to **Status to**.

**Comment by johnp2686** [comment] 2014-05-26 09:06
But i need  separate column on created on ,updated on,status,status to

**Comment by two-pack** [comment] 2014-05-26 09:09
> But i need separate column on created on ,updated on,status,status to

I already separated them by latest commit(5608e9e).
Please check it.

**Comment by johnp2686** [comment] 2014-05-26 09:11
May i know which branch

**Comment by two-pack** [comment] 2014-05-26 09:12
On master.

**Comment by two-pack** [comment] 2014-05-26 09:18
I'm sorry I have a mistake.
I committed on features branch.

**Comment by johnp2686** [comment] 2014-05-26 09:20
ok no problem once you done updated me thanks for your interest

**Closed as completed** 2014-05-26 10:42 UTC
Labels: Enhancement
