### ISSUE TITLE
The URL link of XLS export button is not the root folder of Redmine

### ISSUE THREAD

**Issue by fon1105** [two-pack/redmine_xls_export#94] opened 2015-08-09 13:46 UTC
I can successfully install the plug-in on my Redmine 2.6.3. It works perfectly.
The main problem is that the links of XLS export button is not the root folder of Redmine.
The correct link should be:
http://127.0.0.1/redmine/projects/name/issues_xls_export_current
But it shows the link when I click button:
http://127.0.0.1/projects/name/issues_xls_export_current

How can I change the default root URL? I can't find the related settings.

**Comment by two-pack** [comment] 2015-08-09 21:12
What version of this plugin do you use?

**Comment by fon1105** [comment] 2015-08-09 23:41
I am using 0.2.1.t8. Thanks for your reply.

**Comment by two-pack** [comment] 2015-08-13 01:07
I think this problem related #91 .
Please try this plugin of relaese version which you can download from https://github.com/two-pack/redmine_xls_export/releases/tag/0.2.1.t8

And please more detail of your environment to fix it.
- Using BitNami Redmine, or not
- Config which related url
- and more

**Comment by fon1105** [comment] 2015-08-13 05:17
1. I am not using BitNami Redmine. This is my environment:
   Redmine version                2.6.3.stable
   Ruby version                   1.8.7-p352 (2011-06-30) [i386-linux]
   Rails version                  3.2.21
   Environment                    production
   Database adapter               MySQL
2. I am using apache2 with passenger-3.0.19. This is the HTTP config related Redmine URL
   DocumentRoot "/opt/server"
   RackBaseURI /redmine
   Redmine Directory "/opt/server/redmine/public"
3. I installed this plug-in without attachment function since i am using Ruby 1.8.7.

My HTTP server has others function. I must use http://127.0.0.1/redmine.
Hope you could help me to resolve this problem.

**Comment by two-pack** [comment] 2015-08-13 13:22
fon1105,
I try to fix this problem, but I cannot check it because not to make environment to reproduce it.
I commit to #94 branch, https://github.com/two-pack/redmine_xls_export/tree/%2394
Could you check this branch in your environment?

**Comment by two-pack** [comment] 2015-08-13 13:47
refs http://www.redmine.org/issues/19024

**Comment by fon1105** [comment] 2015-08-13 15:24
You are hero! I already confirm #94 branch fix this problem. Many thanks for your help.

**Comment by two-pack** [comment] 2015-08-13 23:22
fon1105,
Thank you for checking it, I committed the fix.

**Closed as completed by two-pack** 2015-08-13 23:22 UTC
Labels: Bug
